export const POWER_TABLE = {
  "Aumentou todos os Ataques": 34.5,
  "Taxa Crítica": 750,
  "Danos Críticos": 177,
  "Todas as Téc. Amp.": 349,
  "Perfuração": 71,
  "Precisão": 3,
  "Acerto": 6.5,
  "Dano Adicional": 35,
  "Aumento do Dano Final": 1604,
  "Aumento do Dano Normal": 85,
  "Ignorar Bloqueio": 4.5,
  "Ignorar Redução de Danos": 16.8,
  "Ignorar Resistência a Taxa": 574,
  "Ignorar Resistência a Danos Críticos": 142.5,
  "Ignorar Resistência a Técnica de Amp": 267,
  "Cancelar Ignorar Perfuração": 47.8,
  "HP": 5,
  "Defesa": 21,
  "Evasão": 2.4,
  "Bloqueio": 5.3,
  "Redução de Danos": 19.5,
  "Res. Taxa Crítica": 636,
  "Resistência Danos Críticos": 150,
  "Resistência Todas as Téc. Amp.": 296.5,
  "Ignorar Perfuração": 53.1,
  "Ignorar Acerto": 5.3,
  "Dano Final Reduzido": 1451,
  "Desfazer Ignorar Redução de Danos": 19.9,
};

export const STAT_MAP = {
  "PVE Defesa": "Defesa",
  "PVP Defesa": "Defesa",
  "PVE Redução de Danos": "Redução de Danos",
  "PVP Redução de Dano": "Redução de Danos",
  "PVE Ignorar Perfuração": "Ignorar Perfuração",
  "PVE Dano Crítico": "Danos Críticos",
  "PVE Perfuração": "Perfuração",
  'PVE Todas as Técnicas Amp': 'Todas as Téc. Amp.',
  "PVE Todos os Ataques": "Aumentou todos os Ataques",
  "PVE Precisão": "Precisão",
  "PVP Dano Adicionado": "Dano Adicional",
  "PVE Adicionar Dano": "Dano Adicional",
  "PVE Canc. Ig. Red Dano": "Desfazer Ignorar Redução de Danos",
  "PVE Ignorar Acerto": "Ignorar Acerto",
  "PVE Ignorar Bloqueio": "Ignorar Bloqueio",
  "Desfazer Ign. Redução de Dano": "Desfazer Ignorar Redução de Danos",
  "Aum. Dano Ataque Norm": "Aumento do Dano Normal",
  "Ign Res Taxa Crítica": "Ignorar Resistência a Taxa",
  "Ignorar Resistência a Danos Críticos": "Ignorar Resistência a Danos Críticos",
  "Ignorar Resistência à Técnica Amp": "Ignorar Resistência a Técnica de Amp",
  "Aumentou todas as técnicas Amp": "Todas as Téc. Amp.",
  'Resistência à Técnica Amp' : 'Resistência Todas as Téc. Amp.',
  "Aumentou todos os ataques": "Aumentou todos os Ataques",
  'Resistência ao Dano Crítico' : 'Resistência Danos Críticos',
};